"""Render the personal website from reviewed content. No runtime framework required."""
from pathlib import Path
import json,re,html,datetime
ROOT=Path(__file__).resolve().parents[1]
D=json.loads((ROOT/'data/profile.json').read_text())
ALIASES=json.loads((ROOT/'data/legacy-anchors.json').read_text())
REFS=json.loads((ROOT/'data/references.json').read_text())
MEDIA={x['id']:x for x in json.loads((ROOT/'data/awards.json').read_text())}
SEARCH=[]
def e(s):return html.escape(str(s),quote=True)
def date(s):return datetime.date.fromisoformat(s).strftime('%d %B %Y').lstrip('0')
def link(href,text,cls='text-link'):return f'<a class="{cls}" href="{e(href)}">{text}<span aria-hidden="true">↗</span></a>'
def addsearch(title,text,href,kind):SEARCH.append(dict(title=title,text=text,href=href,kind=kind))
def tags(items):return '<div class="tags">'+''.join(f'<a href="/skills/?skill={e(s)}">{e(s.replace("-"," "))}</a>' for s in items)+'</div>'
NAV=[('/#about','About'),('/#experience','Highlights'),('https://www.linkedin.com/in/dultenrpfromentin/','LinkedIn'),('/contact/','Contact')]
MENU=''.join(f'<a href="{u}"><span>{t}</span><span aria-hidden="true">↗</span></a>' for u,t in NAV)
HEADER='''<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="/" aria-label="Dulten Richard Fromentin, home">Dulten Richard<span class="wordmark-dot">.</span></a><nav aria-label="Primary"><a href="/#about">About</a><a href="/#experience">Highlights</a><a href="https://www.linkedin.com/in/dultenrpfromentin/">LinkedIn ↗</a><a href="/contact/">Contact</a></nav><div class="header-tools"><button type="button" class="menu-open" aria-label="Open navigation" aria-controls="site-menu" hidden><span>Menu</span><i aria-hidden="true"></i></button></div></header><div class="reading-progress" aria-hidden="true"></div>'''
FOOTER='''<footer class="site-footer"><div class="footer-top"><a class="footer-name" href="/">Dulten Richard<br /><span>Fromentin.</span></a><div><p class="eyebrow">Brockville, Ontario</p><a href="mailto:fromentindulten@gmail.com">fromentindulten@gmail.com ↗</a><div class="social-links">'''+''.join(f'<a href="{x["url"]}" rel="me noopener noreferrer">{x["label"]} ↗</a>' for x in D['socials'])+'''</div></div></div><nav class="footer-nav" aria-label="All pages">'''+''.join(f'<a href="{u}">{t}</a>' for u,t in NAV)+'''</nav><div class="footer-bottom"><span>© 2026 Dulten Richard Fromentin</span><a href="/privacy/">Privacy &amp; analytics</a><button id="motion-toggle" type="button" aria-pressed="false" hidden>Pause motion</button><a href="#top">Back to top ↑</a></div></footer><dialog id="site-menu" aria-label="Site navigation"><div class="dialog-top"><span>Dulten Richard.</span><button class="dialog-close" type="button" aria-label="Close navigation">Close ×</button></div><nav>'''+MENU+'''</nav><div class="menu-foot">Brockville, Ontario · <a href="https://www.linkedin.com/in/dultenrpfromentin/">Full profile on LinkedIn ↗</a></div></dialog><dialog id="site-search" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">Explore the record.</h2><button class="dialog-close" type="button" aria-label="Close search">Close ×</button></div><label class="sr-only" for="global-search">Search experience, recognition, and years</label><input id="global-search" type="search" placeholder="A role, an award, a year…" autocomplete="off" /><p id="search-status" role="status">Search across this website.</p><div id="search-results"></div></dialog>'''
def page(path,title,description,body,kind=''):
 url='https://dultenrichard.github.io/'+('' if path=='index.html' else path.replace('index.html',''))
 schema={'@context':'https://schema.org','@type':'ProfilePage' if path=='index.html' else 'WebPage','name':title,'url':url,'mainEntity':{'@type':'Person','name':D['name'],'url':'https://dultenrichard.github.io/','sameAs':[x['url'] for x in D['socials']]}}
 if path=='index.html':
  schema['mainEntity'].update({'@id':'https://dultenrichard.github.io/#person','alternateName':['Dulten Richard','Dulten Fromentin'],'image':'https://dultenrichard.github.io/dulten-fromentin-profile.webp','description':D['intro']})
 present=set(re.findall(r'\bid="([^"]+)"',body+HEADER+FOOTER))
 aliases=''.join(f'<span class="anchor-alias" id="{e(a)}" aria-hidden="true"></span>' for a in ALIASES.get(path,[]) if a not in present and a not in ('top','main'))
 display_title='Dulten Richard Fromentin | Leadership & Service' if path=='index.html' else title+' | Dulten Richard Fromentin'
 head=f'''<!doctype html><html lang="en-CA"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>{e(display_title)}</title><meta name="description" content="{e(description)}" /><meta name="author" content="Dulten Richard Fromentin" /><meta name="robots" content="index,follow" /><meta name="theme-color" content="#111b22" /><meta name="referrer" content="strict-origin-when-cross-origin" /><link rel="canonical" href="{url}" /><meta property="og:title" content="{e(display_title)}" /><meta property="og:description" content="{e(description)}" /><meta property="og:type" content="website" /><meta property="og:url" content="{url}" /><meta property="og:image" content="https://dultenrichard.github.io/dulten-fromentin-profile.webp" /><meta name="twitter:card" content="summary" /><link href="/dulten-richard-monogram.png" rel="icon" type="image/png" /><link rel="preload" href="/assets/fonts/newsreader-regular.ttf" as="font" type="font/ttf" crossorigin /><link href="/styles.css?v=5" rel="stylesheet" /><script defer src="/data/site-data.js?v=5"></script><script defer src="/site.js?v=5"></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script>'''
 if path=='index.html':head+='<link rel="preload" as="image" href="/assets/images/water-study.webp" />'
 result=head+f'</head><body class="{kind}" id="top">'+HEADER+'<main id="main">'+body+aliases+'</main>'+FOOTER+'</body></html>\n'
 if path=='projects/index.html':
  result=result.replace('name="robots" content="index,follow"','name="robots" content="noindex,follow"').replace('rel="canonical" href="'+url+'"','rel="canonical" href="https://dultenrichard.github.io/"')
 p=ROOT/path;p.parent.mkdir(exist_ok=True,parents=True);p.write_text(result.replace('><','>\n<'))
def mast(kicker,title,intro,extra=''):
 return f'<section class="page-mast shell"><p class="eyebrow">{kicker}</p><h1 data-reveal>{title}</h1><div class="mast-bottom"><p>{intro}</p>{extra}</div></section>'
def stat(n,label):return f'<div class="fact"><strong>{n}</strong><span>{label}</span></div>'
def boat():return '''<svg class="sail-drawing" viewBox="0 0 640 410" aria-hidden="true"><g class="boat-grid" fill="none" stroke="currentColor" opacity=".13"><path d="M40 85H600M40 165H600M40 245H600M40 325H600M120 30V375M220 30V375M320 30V375M420 30V375M520 30V375"/><circle cx="320" cy="220" r="155"/></g><g fill="none" stroke="currentColor" stroke-width="1.2"><path class="sail-line" d="M324 58V308M315 71L135 278H315ZM337 105L491 278H337ZM98 315H545L487 352H165Z"/><path d="M48 370C103 355 133 388 198 370S299 388 363 370 461 388 582 370" opacity=".5"/><path d="M80 394H565" opacity=".3"/></g><circle cx="324" cy="58" r="4" fill="currentColor"/></svg>'''
# Homepage intentionally shows a few highlights rather than the full resume.
body='''<section class="hero" aria-labelledby="hero-name"><div class="hero-image" aria-hidden="true"></div><div class="hero-shade" aria-hidden="true"></div><div class="hero-content shell"><p class="hero-location">Brockville, Ontario</p><h1 id="hero-name"><span>Dulten</span><em>Richard.</em></h1><p class="hero-surname">Fromentin</p></div><div class="hero-bottom shell"><a href="#about">A little about me <span aria-hidden="true">↓</span></a><a class="hero-linkedin" href="https://www.linkedin.com/in/dultenrpfromentin/" rel="me">Full profile on LinkedIn ↗</a></div></section>'''
body+='''<section class="about-section shell" id="about"><div class="section-index"><span>About</span><span class="fine-rule"></span></div><div class="about-layout"><div class="about-copy"><h2 data-reveal>Interested in people,<br /><em>policy, and service.</em></h2><p data-reveal>I'm a Grade 12 student in Brockville, Ontario, interested in political science, international affairs, and public service. Since joining Air Cadets in 2021, I've moved into instruction and mentoring, alongside school, work, and rugby.</p><a class="text-link" href="https://www.linkedin.com/in/dultenrpfromentin/">More about my experience<span aria-hidden="true">↗</span></a></div><figure class="portrait" data-reveal><img src="/dulten-fromentin-profile.webp" width="360" height="495" alt="Dulten Richard Fromentin" loading="lazy" /><figcaption>Dulten Richard Fromentin<span>Ontario, Canada</span></figcaption></figure></div></section>'''
body+='''<section class="signature-highlights shell" id="experience"><div class="signature-heading"><p class="eyebrow">In brief / 01—03</p><h2 data-reveal>A few things<br /><em>that matter.</em></h2><p>Just the highlights. The full record is on LinkedIn.</p></div><div class="signature-list"><article class="signature-item"><span class="signature-number">01</span><div><p class="eyebrow">Leadership &amp; instruction</p><h3>Royal Canadian Air Cadets.</h3><p>Warrant Officer Second Class. Lord Strathcona Medal, 2026.</p></div><span class="signature-end">2021 — present</span></article><article class="signature-item"><span class="signature-number">02</span><div><p class="eyebrow">Community</p><h3>205 hours of service.</h3><p>Volunteer work and community involvement alongside school and cadets.</p></div><span class="signature-end">Verified</span></article><article class="signature-item"><span class="signature-number">03</span><div><p class="eyebrow">Education &amp; sport</p><h3>Learning through doing.</h3><p>Manufacturing SHSM completed. COSSA rugby silver medalist.</p></div><span class="signature-end">2025–26</span></article></div><a class="signature-link" href="https://www.linkedin.com/in/dultenrpfromentin/" rel="me">See the full experience record on LinkedIn <span aria-hidden="true">↗</span></a></section>'''
body+='''<section class="closing-chapter" id="connect"><div class="shell closing-layout"><div><p class="eyebrow">A thought I keep returning to</p><blockquote id="quote"><p id="leader-liquid-quote">“To be a leader<br />is to be <em>liquid.</em>”</p><footer>Dulten Richard Fromentin</footer></blockquote></div><div class="closing-links"><p>There is more behind the highlights. I keep the full picture elsewhere.</p><a href="https://www.linkedin.com/in/dultenrpfromentin/" rel="me">LinkedIn <span aria-hidden="true">↗</span></a><a href="/contact/">Get in touch <span aria-hidden="true">↗</span></a></div></div></section>'''
page('index.html','Dulten Richard',D['intro'],body,'home')
# Experience
body=mast('Experience','The work,<br /><em>in detail.</em>','Cadet service, employment, community involvement, and education.',link('/assets/documents/Dulten-Richard-Fromentin-Experience.pdf','Download the profile · PDF','button-link'))
body+='<nav class="section-nav shell" aria-label="Experience sections">'+''.join(f'<a href="#{a}">{b}</a>' for a,b in [('cadets','Cadets'),('employment','Work'),('community','Community & sport'),('learning','Education')])+'</nav>'
body+='''<section class="experience-cadets shell" id="cadets"><div class="section-heading"><div><p class="eyebrow">November 2021 — present</p><h2>Royal Canadian<br /><em>Air Cadets</em></h2></div><p>I’ve served with 851 Prince Edward Squadron and 661 Lt W F Sharpe Squadron. My work has grown to include instruction, mentoring, and senior squadron responsibilities.</p></div><div class="cadet-columns"><div><h3>Instruction &amp; mentorship</h3><p>I plan and deliver lessons, mentor junior cadets, and support training, ceremonial activities, and community service. I qualified as a Fitness and Sports Instructor on August 17, 2025.</p><h3>Summer training &amp; staff service</h3><p>I completed CAP 1 in 2022 and CAP 2 in summer 2023. In summer 2026, I served as a Staff Cadet Sergeant at Blackdown, with platoon leadership and company support across training, administration, logistics, and cadet welfare.</p><p>My practical work includes lesson plans, sports setup and officiating, safety checks, and a proposed FSI platoon duty schedule.</p>'''+tags(['leadership','instruction','planning','teamwork'])+'''<details class="plain-details" id="challenge-coins"><summary>Recognition &amp; challenge coins <span>+</span></summary><p>Lord Strathcona Medal, Air Cadet Service Medal, Top Cadet Instructor, Best Physical Fitness, and Legion poppy appreciation. I have received four challenge coins.</p>'''+link('/awards/','The recognition record')+'''</details></div><div class="rank-ladder"><p class="eyebrow">Cadet progression</p>'''+''.join(f'<div class="rank-row" data-reveal><time datetime="{x["date"]}">{date(x["date"])}</time><strong>{e(x["title"])}</strong></div>' for x in D['ranks'])+'''</div></div></section>'''
body+='<section class="employment-section" id="employment"><div class="shell"><div class="section-heading"><div><p class="eyebrow">Employment</p><h2>Working<br /><em>with people.</em></h2></div><p>Retail, donations, and food service.</p></div><div class="jobs">'
for job in D['employment']:
 body+=f'<article class="job" id="{job["id"]}" data-reveal><div class="job-date"><p>{e(job["date"])}</p><span>{e(job["location"])}</span></div><div><h3>{e(job["company"])}</h3><p class="job-role">{e(job["role"])}</p><p>{e(job["body"])}</p>{tags(job["skills"])}</div></article>'
 addsearch(job['company']+' / '+job['role'],job['date']+' '+job['body'],'/experience/#'+job['id'],'Employment')
body+='</div></div></section>'
body+=f'''<section class="community-section shell" id="community"><div class="hours-display"><strong>{D['communityHours']}</strong><span>completed community-involvement hours</span></div><div class="community-copy"><p class="eyebrow">Community &amp; sport</p><h2>Time outside<br /><em>the classroom.</em></h2><p>Marmora Farmers Market, May–September 2022. Dog walking. Cadet poppy campaigns, parades, Remembrance Day events, and helping older community members.</p><p>I took part in Prince Edward County 4-H’s Maple Syrup and Pizza clubs in 2019, and have participated in Rotary’s Adventure in Citizenship.</p><div class="sport-lines"><div><h3>Rugby</h3><p>Flanker. COSSA silver with my school team in 2025; recognised by PECI Athletics for our May 9 win over THS.</p></div><div><h3>Rowing</h3><p>Brockville Rowing Club alumnus. A 7:53.0 result over 2,000 metres at the 2026 Nancy Storrs Ontario Indoor Rowing Championships.</p></div></div>{link('/sources/#public-records','Public records')}</div></section>'''
body+='<section class="education-section shell" id="learning"><div class="section-heading"><div><p class="eyebrow">Education</p><h2>Still learning.</h2></div><p>Grade 12. Manufacturing SHSM completed. Interests in political science, international affairs, and public service.</p></div><div class="education-grid">'
for x in D['education']:body+=f'<article><p class="eyebrow">{e(x["period"])}</p><h3>{e(x["school"])}</h3><p class="status-line">{e(x["status"])}</p><p>{e(x["body"])}</p></article>'
body+='</div><details class="training-details"><summary>Qualifications &amp; course dates <span>+</span></summary><div class="training-table">'+''.join(f'<div><strong>{e(x["name"])}</strong><span>{e(x["issuer"])}</span><time>{e(x["date"])}'+(f' · Listed expiry {x["expiry"]}' if x.get('expiry') else '')+'</time></div>' for x in D['training'])+'</div><p>Experiential Learning, Reach Ahead, and the Sector-Partnered Experience are complete, including Innovation, Creativity and Entrepreneurship training. I also study French, Spanish, Russian, Arabic, and Mandarin as a hobby.</p></details></section>'
page('experience/index.html','Experience','Cadet leadership, employment, education, community service and sport.',body,'experience-page')
# Recognition: native disclosure rows with meaningful filters and request links.
body=mast('Recognition','Awards.<br /><em>And the work behind them.</em>','Cadets, school, advocacy, sport, and community involvement. I keep a copy or proof of each award on file.',link('/sources/#award-proofs','Supporting records'))
body+='<section class="awards-section shell"><div class="filter-bar" data-filter-group="awards" hidden><span class="eyebrow">Show</span>'+''.join(f'<button type="button" data-filter="{x}" aria-pressed="{str(x=="All").lower()}">{x}</button>' for x in ['All','Cadets','School','Sport','Community','Enterprise'])+'</div><p class="result-count" id="award-count" role="status"></p><div class="award-list">'
for i,a in enumerate(D['awards']):
 record=MEDIA.get(a['id'],{}); media=''
 if record.get('image'):media+='<figure class="award-attachment"><img loading="lazy" src="'+e(record['image'])+'" alt="'+e(record.get('alt') or a['title'])+'" /><figcaption>'+e(record.get('caption',''))+'</figcaption></figure>'
 if record.get('document'):media+=link(record['document'],'Open supporting document')
 body+=f'<details class="award-row" id="{a["id"]}" data-category="{a["category"]}"><summary><span class="award-meta">{e(a["meta"])}</span><h2>{e(a["title"])}</h2><span class="award-plus" aria-hidden="true">+</span></summary><div class="award-content"><p>{e(a["body"])}</p>{media}<div><span class="proof-label">{e(a["proof"])}</span>{link("/contact/?topic=Documents&record="+a["id"],"Request supporting record")}</div></div></details>'
 addsearch(a['title'],a['meta']+' '+a['body'],'/awards/#'+a['id'],'Recognition')
body+='</div><p class="records-footnote">The Bright Future entry is a nomination. Program websites explain the awards; my supporting records document my own recognition.</p></section>'
page('awards/index.html','Recognition','Awards and recognition, with dates, context and a route to request supporting evidence.',body,'awards-page')
# The old project URLs remain as a quiet, noindex legacy landing. Project records remain privately in the JSON for later.
body=mast('A smaller public profile','Less, <em>but considered.</em>','This section is not part of my current public website.')
body+='''<section class="page-crosslink shell"><span>For fuller experience and current work</span><a href="https://www.linkedin.com/in/dultenrpfromentin/">Connect on LinkedIn <span aria-hidden="true">↗</span></a></section><span class="anchor-alias" id="equinox" aria-hidden="true"></span><span class="anchor-alias" id="youth-leadership-workshops" aria-hidden="true"></span>'''
page('projects/index.html','Projects paused','This area is no longer featured; explore my short introduction and LinkedIn profile.',body,'projects-paused-page')
# Timeline and each year preserve the full factual record.
body=mast('Timeline','A record<br /><em>over time.</em>','From cadet training to work, service, and education.')
body+='<section class="timeline-shell shell"><nav class="year-nav" aria-label="Choose a year">'+''.join(f'<a href="#year-{y}">{y}</a>' for y in D['years'])+'</nav><div class="year-records">'
for year,items in D['years'].items():
 body+=f'<article class="timeline-year" id="year-{year}"><div class="year-display"><h2>{year}</h2><span>{len(items)} entries</span></div><div class="year-preview">'+''.join(f'<p>{e(x["title"])}</p>' for x in items[:4])+link('/timeline/'+year+'/','Open '+year)+'</div></article>'
 yearbody=mast('The year record',year,'Training, recognition, work, and milestones recorded in '+year+'.',link('/timeline/','All years'))
 yearbody+='<section class="year-detail-list shell">'
 for x in items:
  fact=x['body'] if x.get('kind')!='rank' else ('Joined Air Cadets on ' if x['title']=='Cadet' else 'Promoted on ')+date(x['date'])+'.'
  yearbody+=f'<article id="{x["id"]}" data-reveal><span class="eyebrow">{year}</span><h2>{e(x["title"])}</h2><p>{e(fact)}</p>{link("/sources/","Supporting records")}</article>'
  addsearch(x['title'],year+' '+fact,'/timeline/'+year+'/#'+x['id'],'Year record')
 yearbody+='</section><nav class="year-pagination shell" aria-label="Adjacent years">'+(link('/timeline/'+str(int(year)-1)+'/','← '+str(int(year)-1)) if year!='2019' else '<span></span>')+(link('/timeline/'+str(int(year)+1)+'/',str(int(year)+1)+' →') if year!='2026' else link('/timeline/','All years'))+'</nav>'
 page('timeline/'+year+'/index.html',year+' record','Dulten Richard Fromentin’s record for '+year+'.',yearbody,'year-page')
body+='</div></section>';page('timeline/index.html','Timeline','An archive of training, work, awards and milestones from 2019 through 2026.',body,'timeline-page')
# Skills linked to evidence, with live search rather than self-scored percentages.
body=mast('Skills','Shown<br /><em>through experience.</em>','A skill matters more when there’s something specific behind it.')
body+='<section class="skills-section shell"><div class="skill-controls" hidden><label for="skill-search">Find a skill</label><input id="skill-search" type="search" placeholder="Leadership, research, logistics…" /><button id="clear-skills" type="button">Clear</button><p id="skill-count" role="status"></p></div><div class="skills-list">'
for s in D['skills']:
 body+=f'<article class="skill-record" id="{s["id"]}" data-skill="{s["id"]}"><h2>{e(s["name"])}</h2><div><p>{e(s["text"])}</p><div class="evidence-links">'+''.join(link(x['href'],e(x['text'])) for x in s['links'])+'</div></div></article>'
 addsearch(s['name'],s['text'],'/skills/#'+s['id'],'Skill')
body+='</div><p class="empty-state" id="skill-empty" hidden>No matching skills. Try a broader term.</p></section>';page('skills/index.html','Skills','Leadership, instruction, research and practical skills linked to real examples.',body,'skills-page')
# Records
body=mast('Documents & sources','Behind<br /><em>the record.</em>','My profile, the evidence I keep, and the public sources for the work on this site.')
body=''+body+'''<section class="documents-section shell" id="documents"><a class="document-cover" href="/assets/documents/Dulten-Richard-Fromentin-Experience.pdf" download><div><span class="eyebrow">Download / PDF</span><span aria-hidden="true">↓</span></div><h2>Dulten Richard<br /><em>Fromentin.</em></h2><p>Experience profile</p><div class="document-bottom"><span>Leadership · Work · Service</span><span>3 pages</span></div></a><div class="document-description"><p class="eyebrow">Take a copy</p><h2>A profile<br />you can keep.</h2><p>A designed three-page overview of my cadet service, employment, education, volunteering, sport, recognition, and service.</p>'''+link('/assets/documents/Dulten-Richard-Fromentin-Experience.pdf','Download the PDF')+'''</div></section><section class="proof-section shell" id="private-records"><div><p class="eyebrow">Supporting records</p><h2>Copies.<br /><em>Certificates.<br />Proof.</em></h2><p>I keep a copy or proof of each award listed on this site. You can request the supporting record for a particular item.</p></div><div class="proof-list">'''
for ident,title,txt in [('award-proofs','Award records','Cadet, school, mock-trial, sport, and community recognition.'),('blackdown-reference','Course reference letter','A reference from the 2025 Fitness and Sports course, including course activities and recognition.'),('lesson-plan-record','Fitness & sports lesson plan','EO S234.01: setup, administration, officiating, safety checks, and teardown of a recreational team sport.'),('fsi-planning-record','Duty-schedule memorandum','A proposed 2026 FSI platoon duty schedule, prepared as part of my planning and support work.'),('school-records','School & training records','SHSM completion, course certifications, and 205 community-involvement hours.')]:
 body+=f'<article id="{ident}"><h3>{title}</h3><p>{txt}</p>{link("/contact/?topic=Documents&record="+ident,"Request this record")}</article>'
body+='</div></section><section class="reference-section shell"><div class="section-heading"><h2>Public references.</h2><p>Program sources explain the awards. Public reports and my own records support my participation.</p></div>'
for ref in REFS:body+=ref['html']
body+='</section>';page('sources/index.html','Records & sources','Download the experience profile and request the supporting records behind an award or role.',body,'sources-page')
# Contact: functional mail composer; no implied server submission.
body=mast('Contact','A conversation<br /><em>starts here.</em>','Work, research, mentorship, or a request for supporting records.')
body=f'''{body}<section class="contact-section shell"><div class="contact-direct"><p class="eyebrow">Direct email</p><a class="email-address" href="mailto:{D['email']}">{D['email']}</a><button class="text-button" id="copy-email" type="button" hidden>Copy address</button><p id="copy-status" role="status"></p><p>Brockville, Ontario, Canada</p><div class="contact-socials">'''+''.join(link(x['url'],x['label']) for x in D['socials'])+'''</div><div class="contact-record"><p>Need a certificate or another supporting record?</p>'''+link('/sources/','See the records I keep')+'''</div></div><section class="composer" id="composer" hidden><h2>Write a note.</h2><p>This opens a draft in your email app. Your message isn’t submitted to this website.</p><form id="contact-form"><div class="form-pair"><label>Your name<input id="name" name="name" autocomplete="name" maxlength="100" required /></label><label>Your email<input id="email" name="email" type="email" autocomplete="email" maxlength="200" required /></label></div><label>What is it about?<select name="topic" id="topic"><option value="General">General enquiry</option><option value="Work">Work &amp; opportunities</option><option value="Mentorship">Mentorship &amp; introductions</option><option value="Research">Research</option><option value="Documents">Supporting records</option></select></label><label>Your message<textarea name="message" id="message" rows="5" maxlength="1800" required placeholder="A short introduction and what you have in mind."></textarea></label><button type="submit" class="button-link">Open email draft <span>↗</span></button><p id="form-status" role="status"></p></form></section></section>'''
page('contact/index.html','Contact','Contact Dulten Richard Fromentin about work, research or supporting records.',body,'contact-page')
# Privacy text reflects the actual implementation, including the owner-private review.
body=mast('Privacy','Your choices,<br /><em>clearly stated.</em>','This site uses optional analytics and a local email composer. Updated 10 October 2026.')
body+='''<div class="policy shell"><section id="scope"><h2>What this site does</h2><p>This is my personal website. It presents my experience and provides links to contact me. It has no visitor accounts, advertising profiles, or on-site message database.</p></section><section id="analytics"><h2>Optional analytics</h2><p>Umami Cloud analytics are off until you enable them in this browser. The account uses the EU region. The site honours Global Privacy Control and Do Not Track. Analytics are disabled on the private review domain.</p><p>When enabled on the public site, analytics may measure page views and selected interactions, such as opening navigation, applying a category filter, or downloading a document. Search text, contact messages, names, and email addresses are not sent as event data. URL query strings are excluded.</p><a href="https://docs.umami.is/docs/faq">Umami privacy information ↗</a></section><section id="choices"><h2>Analytics &amp; motion controls</h2><p id="privacy-analytics-status" role="status">Analytics are optional and off by default.</p><div class="privacy-actions"><button id="privacy-enable-analytics" type="button">Enable analytics</button><button id="privacy-disable-analytics" type="button">Disable analytics</button></div><p>These buttons store your choice locally in this browser. The footer’s motion control pauses decorative movement. Reduced-motion preferences from your device are also respected.</p></section><section id="contact-data"><h2>Contact &amp; search</h2><p>The contact composer prepares a mailto draft in your email app. Nothing typed into it is submitted to this website. Search runs locally against this site’s public records. If you send an email, your message is handled by the email services involved.</p></section><section id="hosting"><h2>Hosting</h2><p>The source is maintained on GitHub. This private review is hosted through ChatGPT Sites; the intended public host is GitHub Pages. Hosting providers may process technical request information under their own policies.</p><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement ↗</a></section><section id="retention"><h2>Records &amp; enquiries</h2><p>Supporting certificates and private records are shared individually when appropriate. For a question about information held in correspondence, or to request a correction or deletion, contact <a href="mailto:fromentindulten@gmail.com">fromentindulten@gmail.com</a>.</p></section><section id="third-parties"><h2>External links</h2><p>LinkedIn, Instagram, GitHub, and other linked services operate under their own privacy policies. This website does not embed their tracking widgets.</p></section></div>'''
page('privacy/index.html','Privacy','Analytics preferences, motion controls, hosting, contact data and local search.',body,'privacy-page')
page('404.html','Page not found','The requested page could not be found.',mast('404','A different<br /><em>way back.</em>','That address does not lead to a page on this site.',link('/','Return home','button-link')),'not-found')
for href,title in NAV:addsearch(title,'Explore '+title,href,'Page')
addsearch('Experience profile PDF','Download the three-page experience profile','/assets/documents/Dulten-Richard-Fromentin-Experience.pdf','Document')
(ROOT/'data/search-index.json').write_text(json.dumps(SEARCH,ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/site-data.js').write_text('window.SITE_DATA = '+json.dumps({'search':SEARCH,'updated':D['updated'],'email':D['email']},ensure_ascii=False)+';\n')
(ROOT/'editorial.css').write_text('/* Retained for old cached pages. The rebuilt site uses styles.css. */\n')
print('Rebuilt 18 pages from reviewed content; search index:',len(SEARCH),'entries.')
